### ISSUE TITLE
Ava tests are failed

### ISSUE THREAD

**Issue by TaniaPash** [piercus/semantic-release-verify-deps#2]
branch: [develop](https://github.com/piercus/semantic-release-verify-deps/tree/develop);
latest commit: [here](https://github.com/piercus/semantic-release-verify-deps/commit/75a0b09b05529fd6d5c4c76486295bcd6650d0b6)
travis build : [#6 failed](https://travis-ci.org/piercus/semantic-release-verify-deps/builds/362525755)

#### Actual
1. with npm run test locally exit with errors:
```
started
Promise { <pending> }
  1 failed
  check that normal dependencies are working
  /home/tania/Documents/klap/semantic-release-verify-deps/test/verify-config.js:12
   11:     console.log(res);
   12:   t.is(res, 'fulfilled');
   13: });
  Difference:
  - Promise {}
  + 'fulfilled'
npm ERR! Test failed.  See above for more details.
```
when i'v executed function locally with `node index.js` with console.log (result of function ) i also received `Promise { <pending> }`

2. Travis build errored with:
```

/home/travis/build/piercus/semantic-release-verify-deps/node_modules/ava/cli.js:3
const debug = require('debug')('ava');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

#### Expected 
```
started
Promise { fulfilled }
pkg // additional console.log to be sure that pkg was loaded; 
// test result
```

**Comment by piercus** [comment]
Please close this one if fixed

**Comment by TaniaPash** [comment]
yes, sure.
